train:
  learning_rate: 0.0002
  batch_size: 1
  warmup_ratio: 0.1
  weight_decay: 0.01
  num_special_tokens_in_prefix: 32
  logging_steps: 16
  optim: adamw_8bit
  lr_scheduler_type: linear
  seed: 3407
  save_strategy: "no"
  gradient_accumulation_steps: 1
  fp16: false
  bf16: true
  gradient_checkpointing: true
  remove_unused_columns: false 
  epochs: 1

test:
  batch_size: 1
  max_new_tokens: 64
  temperature: 0.8
  do_sample: false
  top_p: 1.0