stage2:
  model_name: "Qwen/Qwen2-VL-7B-Instruct"
  dataname: "Emotion6"
  test_data_path: "" # your data directory path
  ckpt_path: "../outputs/stage1_train/aspect.pth"      # q_view + cross_attn
  prefix_ckpt_path: "../outputs/stage2_train/emotion6_74.pt"  # trained soft prompt
  prompt_json_path: "../config/prompts/prompts.json" 
  eval_max_new_tokens: 4
  VIEW_NAMES:
    - facial_expression
    - object
    - scene
    - human_action
    - brightness
    - colorfulness
